spring:
  application:
    name: memorizei
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${JAWSDB_URL}
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
  security:
    user:
      name: development
      password: password
